version: '3.9'
services:
  database:
    image: mysql:8.0.28
    ports:
      - "3306:3306"
    restart: always
    environment:
     MYSQL_DATABASE: drexqq
     MYSQL_USER: drexqq
     MYSQL_PASSWORD: asdf1234
     MYSQL_ROOT_PASSWORD: root
  backend:
    image: python:3.9
    ports:
      - "5002:5002"
    restart: always
